image: node:10

stages:
  - test
  - publish

npm-can-publish:
  stage: test
  script:
    - touch ~/.npmrc
    - echo "//registry.npmjs.org/:_authtoken=${NPMJS_PUBLISH_TOKEN}" >> ~/.npmrc
    - npm install -g can-npm-publish
    - can-npm-publish
  only:
    - /^v\d+\.\d+\.\d/

npm-publish:
  stage: publish
  script:
    - touch ~/.npmrc
    - echo "//registry.npmjs.org/:_authtoken=${NPMJS_PUBLISH_TOKEN}" >> ~/.npmrc
    - npm install
    - npm run build
    - npm publish
  only:
    - /^v\d+\.\d+\.\d/
